#ifndef SOC_OPENHWGROUP_CVA6_SOC_OFFSETS_H
#define SOC_OPENHWGROUP_CVA6_SOC_OFFSETS_H

#ifdef CONFIG_SOC_SERIES_CVA6

#ifdef CONFIG_RISCV_SOC_CONTEXT_SAVE

#define GEN_SOC_OFFSET_SYMS()					\
	GEN_OFFSET_SYM(soc_esf_t, cyc_cnt_1)


#endif /* CONFIG_RISCV_SOC_CONTEXT_SAVE */

#endif /* CONFIG_SOC_SERIES_CVA6 */

#endif /* SOC_OPENHWGROUP_CVA6_SOC_OFFSETS_H */